#  MIDS W207 
## Baseline submission
## Authors: Neha Kumar, Suhas Gupta
## Submission Data: 03/16/2019 

In [11]:
# This tells matplotlib not to try opening a new window for each plot.
%matplotlib inline

# General libraries.
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# SK-learn libraries for learning.
from sklearn import preprocessing
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

# SK-learn libraries for evaluation.
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn.metrics import classification_report

We selected the SF Crime competition

https://www.kaggle.com/c/sf-crime/data

In [2]:
## Import CSV files into pandas data frames

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
sample_submission = pd.read_csv('sampleSubmission.csv')


In [3]:
## Lets look at the train data frame
train[:5]

Dates        Category                      Descript  \
0  2015-05-13 23:53:00        WARRANTS                WARRANT ARREST   
1  2015-05-13 23:53:00  OTHER OFFENSES      TRAFFIC VIOLATION ARREST   
2  2015-05-13 23:33:00  OTHER OFFENSES      TRAFFIC VIOLATION ARREST   
3  2015-05-13 23:30:00   LARCENY/THEFT  GRAND THEFT FROM LOCKED AUTO   
4  2015-05-13 23:30:00   LARCENY/THEFT  GRAND THEFT FROM LOCKED AUTO   

   DayOfWeek PdDistrict      Resolution                    Address  \
0  Wednesday   NORTHERN  ARREST, BOOKED         OAK ST / LAGUNA ST   
1  Wednesday   NORTHERN  ARREST, BOOKED         OAK ST / LAGUNA ST   
2  Wednesday   NORTHERN  ARREST, BOOKED  VANNESS AV / GREENWICH ST   
3  Wednesday   NORTHERN            NONE   1500 Block of LOMBARD ST   
4  Wednesday       PARK            NONE  100 Block of BRODERICK ST   

            X          Y  
0 -122.425892  37.774599  
1 -122.425892  37.774599  
2 -122.424363  37.800414  
3 -122.426995  37.800873  
4 -122.438738  37.771541

In [4]:
## Look at the test data frame 
test[:5]

Id                Dates DayOfWeek PdDistrict                   Address  \
0   0  2015-05-10 23:59:00    Sunday    BAYVIEW   2000 Block of THOMAS AV   
1   1  2015-05-10 23:51:00    Sunday    BAYVIEW        3RD ST / REVERE AV   
2   2  2015-05-10 23:50:00    Sunday   NORTHERN    2000 Block of GOUGH ST   
3   3  2015-05-10 23:45:00    Sunday  INGLESIDE  4700 Block of MISSION ST   
4   4  2015-05-10 23:45:00    Sunday  INGLESIDE  4700 Block of MISSION ST   

            X          Y  
0 -122.399588  37.735051  
1 -122.391523  37.732432  
2 -122.426002  37.792212  
3 -122.437394  37.721412  
4 -122.437394  37.721412

(from Kaggle)
## Data fields
- Dates - timestamp of the crime incident
- Category - category of the crime incident (only in train.csv). This is the target variable you are going to predict.
- Descript - detailed description of the crime incident (only in train.csv)
- DayOfWeek - the day of the week
- PdDistrict - name of the Police Department District
- Resolution - how the crime incident was resolved (only in train.csv)
- Address - the approximate street address of the crime incident 
- X - Longitude
- Y - Latitude

The variables we can use to generate the model will need to be in both the train and test dataset. This gives us:
- Dates
- DayOfWeek
- PdDistrict
- Address
- X
- Y

In [33]:
## Split data frames to create data and label numpy arrays
'''
    Convert the pandas data frames to numpy array for using with sklearn.
    We will use the following variable names ->
    X_train: training feature data 
    Y_train: training label data
'''
    
## Split the data frame (category is the predicted variable)
X_train_df = train.drop(['Category','Descript','Resolution'],axis=1)
Y_train_df = pd.DataFrame(train, columns = ['Category'])

## Remove ID column from test data
test_data = test.drop(['Id'],axis=1).values

## Convert data frame to numpy arrays
### change X and Y to features & labels

X_train = X_train_df.values
Y_train = Y_train_df.values
###########################

## Store the feature names in a list
train_features_names = list(X_train_df.keys())

print('Shape of training data: {train_shp1}'.format(train_shp1=X_train.shape))
print('Shape of training labels: {train_shp2}'.format(train_shp2=Y_train.shape))
print('List of training Features:', train_features_names)
print('Shape of test data:', test_data.shape)

Shape of training data: (878049, 6)
Shape of training labels: (878049, 1)
List of training Features: ['Dates', 'DayOfWeek', 'PdDistrict', 'Address', 'X', 'Y']
Shape of test data: (884262, 6)


In [25]:
## Preprocess the categorical data by encoding to numerical values
enc = preprocessing.LabelEncoder()
Y_train_encoded = enc.fit_transform(Y_train.reshape(-1,1))

X_train_encoded = X_train
for k in range(X_train.shape[1]):
    X_train_encoded[:,k] = enc.fit_transform(X_train[:,k].reshape(-1,1))
print(X_train_encoded[:5,:])

/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[389256 6 4 19790 18787 23130]
 [389256 6 4 19790 18787 23130]
 [389255 6 4 22697 19317 32784]
 [389254 6 4 4266 18403 32936]
 [389254 6 5 1843 13848 21892]]


In [29]:
# Getting the data ready for analysis. Here, for the baseline submission, we will just train the model on the latitude and logitude coordinates
def preProcess(df):
    result = df[['X','Y']]
    return result.values

# Shuffle the data using the format shared in class - first creating a list of shuffled indices
random_seed = 1

## Shuffle training data by applying shuffled indices
#train_dev_data = train_dev_data[shuffle_index,:]
#train_dev_labels = train_dev_labels[shuffle_index

# Split into training, dev and mini training data sets
train_data, dev_data, train_labels, dev_labels = train_test_split(
        X_train_encoded, Y_train_encoded, test_size=0.20, random_state=random_seed)
mini_train_data, mini_train_labels = train_data[:1000,:], train_labels[:1000]

print(dev_data.shape)
print(train_data.shape)
print(mini_train_data.shape)

(175610, 6)
(702439, 6)
(1000, 6)


In [30]:
# baseline model is just a knn of 1 for just latitude and longitude
neighbors = 1
kn = KNeighborsClassifier(n_neighbors=neighbors)
kn.fit(mini_train_data, mini_train_labels)

# Create predicted values
#preds_dev = kn.predict(dev_data)
score = kn.score(dev_data, dev_labels)
#proba = kn.predict_proba(dev_data)

print('Mean score from KNN with {nn} neighbors: {score}'.format(nn=neighbors, score=score))

Mean score from KNN with 1 neighbors: 0.1182278913501509


In [10]:
# Define a logistic regression model, train, predict and compute F1 score

# Define linear regression options
solve = 'liblinear'
classes = 'auto'

## Fit, predict & score
LR = LogisticRegression(solver=solve,multi_class=classes)
LR.fit(mini_train_data, mini_train_labels)
LR_predictions = LR.predict(dev_data)
f1Score = metrics.f1_score(dev_labels,LR_predictions,average='weighted')

# Print results
print(train_data.shape)
print("F1-score: {f1}".format(f1=f1Score))

F1-score: 0.2116436654466686


/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [41]:
## Run predictions on test data
test_data_encoded = test_data
for k in range(test_data.shape[1]):
    test_data_encoded[:,k] = enc.fit_transform(test_data[:,k].reshape(-1,1))
preds = kn.predict(test_data_encoded)

/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [39]:
## Print formatted output for submission CSV

# Looking at format of output
#print(sample_submission.head())

# Now put results in a dataframe 
all_ids = test["Id"].values
d = {'Id': all_ids, 'Label': preds}

# Make the results dummy columns
df = pd.DataFrame(data = d)
results = pd.get_dummies(df, prefix=[''],prefix_sep = '')

# To ensure we have all columns, copy data into the schema of sample_submission
submission = pd.DataFrame().reindex_like(sample_submission).fillna(0).astype(int)

col_names = list(results.columns.values)
for col in col_names:
    submisssion[col] = results[col]

    
#print('final shape',my_submission.shape )
#my_submission.to_csv('my_submission_practice_nk1.csv', index = False)

print(submission)

ValueError: Length of 'prefix' (1) did not match the length of the columns being encoded (0).

In [ ]:
# For later, we wil consider adding these into our preProcesser function
# train['Dates'] = pd.to_datetime(train['Dates'],infer_datetime_format=True)
# train["dow"] = train["Dates"].dt.dayofweek
# train["unix_date"] = train['Dates'].astype(np.int64) // 10 ** 9
# PdDistrict = pd.factorize(train["PdDistrict"])
# pd_ids = PdDistrict[0]
# pd_names = PdDistrict[1]
# print(pd_names)
# print(train.dtypes)
# print(train.head())